// Mocks generated by Mockito 5.3.2 from annotations
// in line_up/test/auth_all_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:line_up/infrastructure/auth/data_source/remote/api_client/http_client.dart'
    as _i2;
import 'package:line_up/infrastructure/auth/dto/response/user/user_dto.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthHttpClient extends _i1.Mock implements _i2.AuthHttpClient {
  MockAuthHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get loginPath => (super.noSuchMethod(
        Invocation.getter(#loginPath),
        returnValue: '',
      ) as String);
  @override
  _i3.Future<_i4.UserDto>? login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #login,
        [
          username,
          password,
        ],
      )) as _i3.Future<_i4.UserDto>?);
}
