// import 'package:equatable/equatable.dart';

// /// generate by https://javiercbk.github.io/json_to_dart/
// class AutogeneratedYouAwesome1 {
//   final List<YouAwesome1Model> results;

//   AutogeneratedYouAwesome1({required this.results});

//   factory AutogeneratedYouAwesome1.fromJson(Map<String, dynamic> json) {
//     var temp = <YouAwesomeModel>[];
//     if (json['results'] != null) {
//       temp = <YouAwesome1Model>[];
//       json['results'].forEach((v) {
//         temp.add(YouAwesome1Model.fromJson(v as Map<String, dynamic>));
//       });
//     }
//     return AutogeneratedYouAwesome1(results: temp);
//   }

//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['results'] = results.map((v) => v.toJson()).toList();
//     return data;
//   }
// }

// class YouAwesome1Model extends Equatable {
//   final int id;
//   final String name;

//   YouAwesome1Model(this.id, this.name);

//   @override
//   List<Object> get props => [id, name];

//   factory YouAwesome1Model.fromJson(Map<String, dynamic> json) {
//     return YouAwesome1Model(json['id'] as int, json['name'] as String);
//   }

//   Map<String, dynamic> toJson() {
//     final data = <String, dynamic>{};
//     data['id'] = id;
//     data['name'] = name;
//     return data;
//   }
  
// }
